"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tema8_1 = require("./tema8");
var vector1 = new tema8_1.Vector(2, 6);
vector1.print();
var a = new tema8_1.Vector(2, 4);
var b = new tema8_1.Vector(2, 5);
var n = 1;
console.log(a.add(b));
console.log(a.subs(b));
console.log(a.multNumber(n));
